### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [marcusvolz/mathart#1]
Fantastic package!  I recommend possibly relaxing this requirement:

```
ERROR: this R is version 3.4.3, package 'mathart' requires R >= 3.4.4
Installation failed: Command failed (1)
```

**Comment by marcusvolz** [comment]
Thanks, I changed it to 3.4.3. In the R Packages book it is recommended to require a version greater than or equal to the version you’re currently using (see http://r-pkgs.had.co.nz/description.html#version), but hopefully there are no issues here.

**Comment by happyshows** [comment]
Hi,

Does this package really depends on 3.4.3?

If it's nice to have, can you switch it to suggests instead of depends?

**Comment by marcusvolz** [comment]
Changed to suggests.
