### ISSUE TITLE
mathart export to SVG

### ISSUE THREAD

**Issue by Shornone** [marcusvolz/mathart#3]
Currently saves beautiful PNG files. I would love to be able to save those generated images as an SVG so I could plot them.

Nice work thanks for sharing!

**Comment by marcusvolz** [comment]
Hi Shornone, you should be able to just change the file name extension to svg instead of png in the ggsave function.

**Comment by Shornone** [comment]
You are right. I had to install svglite and could just do that. The files were huge though.

Thanks for the quick reply.
