### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by markhogue** [marcusvolz/mathart#4]
Installation with devtools fails with or without commit number. Showing below with a 9 month old commti, but I tried lots in between:
`devtools::install_github(repo = "marcusvolz/mathart", commit = "2ca706c") ` 

Error in read.dcf(path) : 
  Found continuation line starting '    person("Marcus", ...' at begin of record.

By contrast, 
`devtools::install_github(repo = "marcusvolz/ggart") `  
works fine. One difference is the DESCRIPTION file has only one authors@R line.

**Comment by mas192** [comment]
Please help, function not found error
 #Create mollusc shells
> #The shell model is described in the paper "Models for mollusc shell shape" by M.B. Cortie (1989).
> 
> df <- mollusc()
Error in mollusc() : could not find function "mollusc"
> df1 <- df %>% mutate(id = 1)
Error in df %>% mutate(id = 1) : could not find function "%>%"
> df2 <- df %>% mutate(id = 2)
Error in df %>% mutate(id = 2) : could not find function "%>%"
> df3 <- df %>% mutate(id = 3)
Error in df %>% mutate(id = 3) : could not find function "%>%"
> 
> p <- ggplot() +
+   geom_point(aes(x, y), df1, size = 0.03, alpha = 0.03) +
+   geom_path( aes(x, y), df1, size = 0.03, alpha = 0.03) +
+   geom_point(aes(x, z), df2, size = 0.03, alpha = 0.03) +
+   geom_path( aes(x, z), df2, size = 0.03, alpha = 0.03) +
+   geom_point(aes(y, z), df3, size = 0.03, alpha = 0.03) +
+   geom_path( aes(y, z), df3, size = 0.03, alpha = 0.03) +
+   facet_wrap(~id, nrow = 2, scales = "free") +
+   theme_blankcanvas(margin_cm = 0.5)
Error in fortify(data) : object 'df1' not found

**Comment by marcusvolz** [comment]
Mark, I don't seem to get this problem when I do a fresh install. It looks like it has something to do with https://github.com/r-lib/devtools/issues/1900 - I've removed indentations in the description file so maybe that will work.

**Comment by marcusvolz** [comment]
mas192 - I'm not sure why you are getting those errors. Have you loaded the packages?
library(mathart)
library(ggart)
library(ggforce)
library(Rcpp)
library(tidyverse)

**Comment by mas192** [comment]
Yes, I did!!

**Comment by mas192** [comment]
I'll reinstall mathart and see if it fixes it

**Comment by mas192** [comment]
I see all the variable, but now I dont see the plot, sorry, 
df <- mollusc()
df1 <- df %>% mutate(id = 1)
df2 <- df %>% mutate(id = 2)
df3 <- df %>% mutate(id = 3)

p <- ggplot() +
  geom_point(aes(x, y), df1, size = 0.03, alpha = 0.03) +
  geom_path( aes(x, y), df1, size = 0.03, alpha = 0.03) +
  geom_point(aes(x, z), df2, size = 0.03, alpha = 0.03) +
  geom_path( aes(x, z), df2, size = 0.03, alpha = 0.03) +
  geom_point(aes(y, z), df3, size = 0.03, alpha = 0.03) +
  geom_path( aes(y, z), df3, size = 0.03, alpha = 0.03) +
  facet_wrap(~id, nrow = 2, scales = "free") +
  theme_blankcanvas(margin_cm = 0.5)

ggsave("mollusc01.png", width = 80, height = 80, units = "cm")

am I doing something wrong?

**Comment by marcusvolz** [comment]
Is there not a png file called "mollusc01.png" in your working directory? (Type getwd() to see where your working directory is.)

**Comment by mas192** [comment]
Yes I see the file but is empty

**Comment by marcusvolz** [comment]
ggsave can take some time to generate the plot (5+ minutes on my machine). In the meantime it might look like an empty file. It seems to work ok on my machine - sorry I can't be of more help.

**Comment by mas192** [comment]
Oh okay that makes, sense, thanks!!!!

**Comment by mas192** [comment]
you are right it worked, thanks
![mollusc01](https://user-images.githubusercontent.com/21248222/52910095-6af4b680-3247-11e9-919a-02ef1b3aa411.png)

**Comment by markhogue** [comment]
Thank you so much, Marcus. It works now. 
Sorry I took so long to reply. I'm new to github and thought I was going to see a notification in my email.
