### ISSUE TITLE
Less intensive mollusc-shell example?

### ISSUE THREAD

**Issue by dwbapst** [marcusvolz/mathart#5]
Howdy,

I love the Raup-esque mollusc shell visualization (Dave Raup was one of the more prominent figures in modeling shell growth), but I'm curious if you could provide an example that was less system intensive? Even one shell, rather than all three as in your example, is pretty laborious for a laptop with a lot of memory, and I'd like to use it in a classroom environment. I'm not sure I understand at what resolution the visual is being generated, though, or if that's even the main bottleneck.

Really fantastic work, though, and I've enjoyed playing around with this package quite a bit!

**Comment by marcusvolz** [comment]
Hi David,

Reducing the n_s and n_t parameters in mollusc, removing alpha and increasing the line and point size gives quite a nice plot that only takes a few seconds to generate, i.e.

df <- mollusc(n_s = 100, n_t = 400)

p <- ggplot() +
  geom_point(aes(x, y), df, size = 0.25) +
  geom_path( aes(x, y), df, size = 0.25) +
  theme_blankcanvas(margin_cm = 0.5) +
  coord_equal()

ggsave("mollusc01.png", width = 80, height = 80, units = "cm")

![mollusc01](https://user-images.githubusercontent.com/12025275/53219452-1e303600-36b4-11e9-8ae9-4c795703b516.png)
