### ISSUE TITLE
ggart?

### ISSUE THREAD

**Issue by mermustangii** [marcusvolz/mathart#6]
The ggart thing is no longer on github and can't be pulled on R.  I'm a bit of a noob so I don't know how to pull it off rdrr.io.

**Comment by marcusvolz** [comment]
ggart isn't actually needed anymore, so I just removed it from the readme

**Comment by ghost** [comment]
Hey Marcus,

it seems your "Metropolis" script (https://github.com/marcusvolz/metropolis/blob/master/metropolis.R, great art, by the way! :)) still uses ggart. Is ggart actually needed for this piece of art?

**Comment by marcusvolz** [comment]
Hi Chris, I just updated the file (removed ggart and updated the theme settings), so hopefully it should work now.
